version: "3.9"
services:
  web:
    build:
      context: .
      dockerfile: ./web/Dockerfile
    container_name: web
    environment:
      - CHOKIDAR_USEPOLLING=true
    volumes:
      - ./web/src:/app/src
  nginx:
    build:
      context: .
      dockerfile: ./nginx/Dockerfile
    container_name: nginx
    ports:
      - 8081:8081
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
